---
title: "Text mining of COVID-19"
author: "Jianfeng Li"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    toc: true
    theme: cayman
    highlight: github
---

```{r, echo = FALSE}
knitr::opts_chunk$set(comment = "#>", collapse = TRUE, screenshot.force = FALSE)
library(openxlsx)
```

## PubMed data mining

### Meta

```{r echo=FALSE, message=FALSE, warning=FALSE}
raw_cor <- jsonlite::read_json("../cor/raw.json")
x <- as.data.frame(t(sapply(raw_cor, function(x){
  tmp <- x[c(1,2,3,5,8,4)]
  return(tmp)
})))
DT::datatable(x, extensions = c("Buttons", "FixedColumns", "Responsive"),
              options = list(autoWidth = TRUE, scrollX=FALSE, dom = "Bfrtlip", deferRender = TRUE,
                   searchHighlight = TRUE, columnDefs = list(list(width="100px", targets="_all"))))
```

### Label with countries and cities

```{r, echo=FALSE, message=FALSE, warning=FALSE}
countries_cities <- read.xlsx("../cor/abs_countries_cities.xlsx")
countries_cities <- countries_cities[order(countries_cities$Correlation),]
DT::datatable(countries_cities[,c(1,3,4)], extensions = c("Buttons", "FixedColumns", "Responsive"))
```

### Label with genes

```{r, echo=FALSE, message=FALSE, warning=FALSE}
genes <- read.xlsx("../cor/abs_genes.xlsx")
genes <- genes[order(genes$Correlation),]
DT::datatable(genes[,c(1,3,4)], extensions = c("Buttons", "FixedColumns", "Responsive"))
```
